Summary:	GNOME Desktop Suite
Summary(pl):	¦rodowisko graficzne GNOME
Name:		metapackage-gnome
Version:	2.8.1
Release:	1
License:	GPL
Group:		X11/Applications/Desktop
Requires:	bug-buddy >= 2.8.0
Requires:	control-center >= 1:2.8.1
Requires:	dasher >= 3.2.11
Requires:	eel >= 2.8.1
Requires:	eog >= 2.8.1
Requires:	epiphany >= 1.4.5
Requires:	evolution >= 2.0.2
Requires:	evolution-addressbook >= 2.0.2
Requires:	evolution-calendar >= 2.0.2
Requires:	evolution-mail >= 2.0.2
Requires:	evolution-pilot >= 2.0.2
Requires:	evolution-data-server >= 1.0.2
Requires:	evolution-webcal >= 2.0.1
Requires:	file-roller >= 2.8.3
Requires:	gal >= 1:2.2.3
Requires:	gcalctool >= 4.4.20
Requires:	gconf-editor >= 2.8.2
Requires:	gdm >= 1:2.6.0.5
Requires:	gdm-Xnest >= 1:2.6.0.5
Requires:	gedit2 >= 2.8.1
Requires:	ggv >= 2.8.0
Requires:	gnome-applets >= 1:2.8.1
Requires:	gnome-desktop >= 2.8.1
Requires:	gnome-games >= 1:2.8.1
Requires:	gnome-games-blackjack >= 1:2.8.1
Requires:	gnome-games-gataxx >= 1:2.8.1
Requires:	gnome-games-glines >= 1:2.8.1
Requires:	gnome-games-gnect >= 1:2.8.1
Requires:	gnome-games-gnibbles >= 1:2.8.1
Requires:	gnome-games-gnobots2 >= 1:2.8.1
Requires:	gnome-games-gnometris >= 1:2.8.1
Requires:	gnome-games-gnomine >= 1:2.8.1
Requires:	gnome-games-gnotravex >= 1:2.8.1
Requires:	gnome-games-gnotski >= 1:2.8.1
Requires:	gnome-games-gtali >= 1:2.8.1
Requires:	gnome-games-iagno >= 1:2.8.1
Requires:	gnome-games-mahjongg >= 1:2.8.1
Requires:	gnome-games-same-gnome >= 1:2.8.1
Requires:	gnome-games-sol >= 1:2.8.1
Requires:	gnome-games-stones >= 1:2.8.1
Requires:	gnome-icon-theme >= 2.8.0
Requires:	gnome-keyring >= 0.4.0
Requires:	gnome-mag >= 0.11.10
Requires:	gnome-media >= 2.8.0
Requires:	gnome-netstatus >= 2.8.0
Requires:	gnome-nettool >= 0.99.3
Requires:	gnome-panel >= 2.8.1
Requires:	gnome-session >= 2.8.1
Requires:	gnome-speech >= 0.3.5
Requires:	gnome-system-monitor >= 2.8.0
Requires:	gnome-system-tools >= 1.0.0
Requires:	gnome-terminal >= 2.8.0
Requires:	gnome-themes >= 2.8.1
Requires:	gnome-themes-Crux >= 2.8.1
Requires:	gnome-themes-Flat-Blue >= 2.8.1
Requires:	gnome-themes-Glider >= 2.8.1
Requires:	gnome-themes-Grand-Canyon >= 2.8.1
Requires:	gnome-themes-HighContrast >= 2.8.1
Requires:	gnome-themes-HighContrastInverse >= 2.8.1
Requires:	gnome-themes-HighContrastLargePrint >= 2.8.1
Requires:	gnome-themes-HighContrastLargePrintInverse >= 2.8.1
Requires:	gnome-themes-LargePrint >= 2.8.1
Requires:	gnome-themes-LighthouseBlue >= 2.8.1
Requires:	gnome-themes-LowContrast >= 2.8.1
Requires:	gnome-themes-LowContrastLargePrint >= 2.8.1
Requires:	gnome-themes-Mist >= 2.8.1
Requires:	gnome-themes-Ocean-Dream >= 2.8.1
Requires:	gnome-themes-Sandwish >= 2.8.1
Requires:	gnome-themes-Sandy >= 2.8.1
Requires:	gnome-themes-Simple >= 2.8.1
Requires:	gnome-themes-Smokey >= 2.8.1
Requires:	gnome-themes-Smokey-Blue >= 2.8.1
Requires:	gnome-themes-Smokey-Red >= 2.8.1
Requires:	gnome-themes-ThinIce >= 2.8.1
Requires:	gnome-themes-Traditional >= 2.8.1
Requires:	gnome-utils >= 1:2.8.1
Requires:	gnome-volume-manager >= 1.0.2
Requires:	gnome2-user-docs >= 2.8.1
Requires:	gnomemeeting >= 1.0.2
Requires:	gnopernicus >= 0.9.18
Requires:	gok >= 0.11.12
Requires:	gpdf >= 2.8.0
#Requires:	gstreamer-plugins >= 0.8.5
#Requires:	gstreamer >= 0.8.7
Requires:	gtk2-engines >= 1:2.2.0
Requires:	gtkhtml >= 3.2.3
Requires:	gtksourceview >= 1.1.1
Requires:	gucharmap >= 1.4.2
Requires:	libgail-gnome >= 1.1.0
Requires:	libgtkhtml >= 2.6.2
Requires:	libgtop >= 1:2.8.1
Requires:	librsvg >= 1:2.8.1
Requires:	libsoup >= 2.2.1
Requires:	libwnck >= 2.8.1
Requires:	libxklavier >= 1.04
Requires:	metacity >= 2:2.8.6
Requires:	metacity-themes-AgingGorilla >= 2:2.8.6
Requires:	metacity-themes-Atlanta >= 2:2.8.6
Requires:	metacity-themes-Bright >= 2:2.8.6
Requires:	metacity-themes-Crux >= 2:2.8.6
Requires:	metacity-themes-Esco >= 2:2.8.6
Requires:	metacity-themes-Metabox >= 2:2.8.6
Requires:	metacity-themes-Simple >= 2:2.8.6
Requires:	nautilus >= 2.8.1
Requires:	nautilus-cd-burner >= 2.8.4
#Requires:	nautilus-media >= 0.8.1
Requires:	scrollkeeper >= 1:0.3.14
Requires:	startup-notification >= 0.7
Requires:	vino >= 2.8.1
Requires:	vte >= 0.11.11
Requires:	ximian-connector >= 2.0.2
Requires:	yelp >= 2.6.4
Requires:	zenity >= 2.8.1
Requires:	hal >= 0.4.1
Requires:	xscreensaver-gnome2 >= 1:4.18
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
GNOME Desktop suite metapackage.

%description -l pl
Metapakiet ¶rodowiska graficznego GNOME.

%files
